### ISSUE TITLE
3.6.10: Updated Amazon AWS SDK for S3 services is using too much memory.

### ISSUE THREAD

**Issue by robgeorgeuk** [inpsyde/backwpup#105]
See: https://wordpress.org/support/topic/plugin-is-exhausting-total-server-memory-uploading-to-s3/

This issue exists in all versions since 3.6.10. Please consider updating the AWS SDK to resolve this issue.

**Comment by cuongdcdev** [comment]
@robgeorgeuk 
Please help us try the new version which fixed S3 thank you so much!
https://www.dropbox.com/s/hcd4p5tr37m1ivc/backwpup-1474.zip?dl=0
Looking forward to hearing new feedback from you ^^

**Comment by robgeorgeuk** [comment]
@cuongdcdev Thanks for your quick response and updated plugin but sadly it didn't fix the issue.
For clarity, this issue doesn't occur on 3.6.9 but it does on 3.7.1 and the new version that you have linked above. I've attached my anonymised log file.
[BackWPUp.log](https://github.com/inpsyde/backwpup/files/4752516/BackWPUp.log)

**Comment by cuongdcdev** [comment]
@robgeorgeuk 
hmm, can you help me to increase the max memory limit to 512mb then try again? 
Thanks!

**Comment by robgeorgeuk** [comment]
@cuongdcdev I can try, below are the memory values, the PHP Memory Limit is set by the host I believe.

PHP Memory limit | 255M
WP memory limit | 512M
WP maximum memory limit | 512M

The backup job still fails as before :-(

**Comment by cuongdcdev** [comment]
@robgeorgeuk which s3 destination did you running?, also, can you change the PHP mem limit to about 512mb first then try again?

**Comment by robgeorgeuk** [comment]
@cuongdcdev Sadly I have no access on this host to increase the PHP Memory limit :-(

**Comment by cuongdcdev** [comment]
@robgeorgeuk 
Could you please help me test the new path? 
Just override the content of `wp-content/plugins/backwpup/inc/class-destination-s3.php` with the one here:  https://gist.github.com/cuongdcdev/6a751d4312f8e6ac056294ee638cb71b

TY!

**Comment by robgeorgeuk** [comment]
@cuongdcdev 

Hi,

Sadly the backup still failed but I think it's a different error. I've attached the log.

[BackWPUp-20-10-05.log](https://github.com/inpsyde/backwpup/files/5328802/BackWPUp-20-10-05.log)

**Comment by cuongdcdev** [comment]
@robgeorgeuk 
thank you for testing, please help me test this instead: https://www.dropbox.com/s/58cskckxg6ark65/backwpup_mem_leak..zip?dl=0
just download then install the patched version of BWU. then run again.
Thank you so much!

**Comment by cuongdcdev** [comment]
The issue closed because I got no response for a long time.
