### ISSUE TITLE
Bucket not found for Digital Ocean Spaces

### ISSUE THREAD

**Issue by asmerkin** [inpsyde/backwpup#107]
I'm trying to setup Digital Ocean Spaces. 

- I'm using the s3 URL nyc3.digitaloceanspaces.com
- It pulls the buckets I have in s3. 
- I can select the right bucket and save it normally. 
- I can run my backup job. 
- Everything works fine, until it reaches to the upload point. It says it cannot find the bucket with the name selected from the dropdown. 

Can you help me?

**Comment by cuongdcdev** [comment]
Hello @asmerkin 
Please help me try this version instead: https://www.dropbox.com/s/hcd4p5tr37m1ivc/backwpup-1474.zip?dl=0
After that, go to AWS S3 tab -> configure your Digital Ocean Space in **Or an S3 Server URL**
Thank you!

**Comment by asmerkin** [comment]
In fact I just dismissed spaces. So I no longer need this. I'm just using AWS S3. Thank you anyway!
