### ISSUE TITLE
Copy.com Integration

### ISSUE THREAD

**Issue by Shepstar** [inpsyde/backwpup#23]
Hey,
I really like backwpup but unfortunately I had to choose a different one because you only have a dropbox integration in the free version and no copy.com. Copy.com offers 15 GB for free which is a lot compared to dropbox.
Perhaps you could integrate copy.com for the next version which would be great.
Thanks.

**Comment by sebastian-blum** [comment]
As Barracu won't develop copy anymore and shut down copy.com at 01.05.2016, an integration is void. 

more info on:
https://www.copy.com/
https://blog.barracuda.com/2016/02/01/message-from-gm-of-storage/
