### ISSUE TITLE
Log file incomplete

### ISSUE THREAD

**Issue by pedro-mendonca** [inpsyde/backwpup#35]
Hi @danielhuesken ,

I have BackWPup in several WordPress installs, a few days a go I've came across something new.
I installed the plugin for the first time on a site, and it installed the current v3.2.4.
After the settings roundup and creating the first job with the default *Normal (translated)* log, the log just write the first 4 lines, the last one is "type is archive". After that, nothing. If I change the type of log to debug it writes a perfeclty complete log.

As I'm used to Normal log being ok, I've compared to other WordPress installs. They were working perfect. But one thing bothers me, it's the same version, current version of BackWPup.

Probably the issue is not recent, somehow it was masked by old settings in my database, because after I've changed from Normal to Debug and then from Debug to Normal again, in the WordPress installs that were working fine with Normal logs, it just stopped working, exactly as the recently new install where I found this issue.

I've checked the Normal translated and not translated, and the problem is the same.

A final suggestion, to be a little more clear, maybe there could be added a line in the header of the log mentioning wich mode it is made in.
ex.:
[INFO] Log Level: Normal (translated)

Best regards

**Comment by danielhuesken** [comment]
The first INFO lines will be created if the job creates. After creation the job will started and that shuld not be work in your case.

The log level info will be added in the next update.

**Comment by pedro-mendonca** [comment]
I'm not sure what happened, but the normal log now appears correct and complete. I'm closing this because it might not be caused by BackWPup.
Thanks.
