### ISSUE TITLE
Change Admin bar menu item to default:off

### ISSUE THREAD

**Issue by jeffmcneill** [inpsyde/backwpup#40]
In settings uncheck the box and hit save, but it just refreshes and keeps the old setting. Please let me know how to remove BackWPup from the admin bar. Note, this is in multisite and single site

I had to wipe out line 99 in backwpup.php, for now, but surely the next update will overwrite that. It would be great if the admin bar menu were an option with a default of OFF, but certainly the inability to change the state is bug at this point.

Daniel said he was willing to change Admin bar menu item to default:off and then check to see if the toggle worked properly at that point.

Original report filed at: https://wordpress.org/support/topic/cannot-remove-backwpup-from-admin-bar?replies=7#post-8525289

**Comment by danielhuesken** [comment]
I have implemented it. The release came soon. Please test it than again.

**Comment by sebastian-blum** [comment]
Works fine
