### ISSUE TITLE
BackWPup user meta stored after plugin has been removed

### ISSUE THREAD

**Issue by pixolin** [inpsyde/backwpup#42]
A user reported on the German WordPress support forums, that the user capabilities for BackWPup still are shown after deactivating and removing BackWPup. The value of the capability (e.g. `backwpup_admin`) is stored as serial data for key `wp_capabilities` in table `wp_usermeta` and should be cleared upon plugin uninstall.

Props @te-punkt, thread [BackWPup: Zusätzliche Befugnisse löschen, wie?](https://de.wordpress.org/support/topic/backwpup-zusaetzliche-befugnisse-loeschen-wie/#post-33056).

**Comment by widoz** [comment]
Hi @pixolin there is already a pull request to solve this https://github.com/inpsyde/backwpup/pull/50 hope will be included asap.
