### ISSUE TITLE
Tweak

### ISSUE THREAD

**Issue by colomet** [inpsyde/backwpup#44]
I don´t use to use the backwpup dashboard all the time, just when it is necesary. It will not be better if the menu is inside of tools?

![captura de pantalla 2017-02-14 a las 11 57 52](https://cloud.githubusercontent.com/assets/3929177/22926459/ee792eaa-f2ac-11e6-94cd-24df8d8751e3.png)

thanks

**Comment by widoz** [comment]
Hi @colomet move all of the menu items under the *Tools* isn't possible because WordPress admin menu cannot have more than 2 levels.
