### ISSUE TITLE
"tar" long filename support

### ISSUE THREAD

**Issue by mundschenk-at** [inpsyde/backwpup#54]
`BackupWP_Create_Archive::tar_file` should support the GNU long filename extension (instead of being [limited to 99 characters](https://github.com/inpsyde/backwpup/blob/7fe26736c137e46e63c42fd90bc0e885fad66baf/inc/class-create-archive.php#L457)). Using the "zip" format as a workaround is not feasible for image backups, as it takes a very long time without any benefits (double compression).

**Comment by widoz** [comment]
Hi @mundschenk-at tar archive have limitation in terms of maximum length for paths. 
At the time tar was implemented there was a limitation of 99 characters, see the man page https://www.gnu.org/software/tar/manual/html_section/tar_67.html

**Comment by mundschenk-at** [comment]
@widoz Well yes, that's why I created this feature request. Everybody uses GNU tar nowadays, and `gnu` format supports longer filenames. Alternatively, the `posix` format would work as well - though I'm not sure how widespread support for that is. Fortunately, it contains a backwards-compatible layer, so it could be read as a `ustar` archive (which is what you are creating now).
