### ISSUE TITLE
Allow PathStyle for S3

### ISSUE THREAD

**Issue by noplanman** [inpsyde/backwpup#57]
Using minio as an S3 provider, the connection to the bucket fails, because the PathStyle cannot be set to true.

Using the direct IP of my minio instance, BackWPup tries this:
`http://bucket.1.2.3.4`
instead of this:
`http://1.2.3.4/bucket`

Would be nice to have this as an option 👍

**Comment by widoz** [comment]
@noplanman This refers to #58 right?

**Comment by noplanman** [comment]
@widoz Yes!
