### ISSUE TITLE
wp-cron.php was not found on this server

### ISSUE THREAD

**Issue by ROvERenTHOReguN** [inpsyde/backwpup#59]
I get the following error:

WP-Cron url: https://www.jaimiorganiseert.nl/wp-cron.php
Server self connect: Not expected HTTP response:
Status-Code: 404
Date: Wed, 20 Dec 2017 08:30:09 GMT
Server: Apache
Content-length: 328
Content-type: text/html; charset=iso-8859-1
Content: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /wp-cron.php was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

However: the wp-cron.php is in place and is accepted if called with the URL itself.

What could this be? Thank you!

**Comment by te-online** [comment]
I get a 500 for wp-cron caused by BackWPUp, I think. Maybe your server returns a 404 instead and has the same error?

```
Got error 'PHP message: PHP Fatal error: Uncaught Error: Cannot use object of type WP_Error as array in /var/www/vhosts/[domain removed]/httpdocs/wp-content/plugins/backwpup/inc/class-cron.php:142
Stack trace:
#0 /var/www/vhosts/[domain removed]/httpdocs/wp-includes/class-wp-hook.php(286): BackWPup_Cron::update_message()
#1 /var/www/vhosts/[domain removed]/httpdocs/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /var/www/vhosts/[domain removed]/httpdocs/wp-includes/plugin.php(515): WP_Hook->do_action(Array)
#3 /var/www/vhosts/[domain removed]/httpdocs/wp-cron.php(126): do_action_ref_array('backwpup_update...', Array)
#4 {main}
thrown in /var/www/vhosts/[domain removed]/httpdocs/wp-content/plugins/backwpup/inc/class-cron.php on line 142
```

**Comment by widoz** [comment]
Hi @ROvERenTHOReguN do you still have the problem? Have you checked you have the file `wp-cron.php` under the root of WordPress and it's readable? This is a builtin file of WordPress.

@te-online Sounds like your issue is a different one, if you still experiencing it please open a different issue. Also, please check the latest 3.6.7 version to see if the problem has been solved.

**Comment by cuongdcdev** [comment]
no response so I mark it as closed.
