### ISSUE TITLE
S3 Bucket “s3://bucket-name” does not exist!

### ISSUE THREAD

**Issue by swapnil2sutar** [inpsyde/backwpup#60]
Hello,

I am using amazon s3 to store backups using backwpup, But I am receiving errors while running job “S3 Bucket “s3://os-website-backup” does not exist!”

My credentials are correct & verified. Also tried by changing region. but no luck.

What would be the issue?

Thanks in Advance ..!!

**Comment by danielhuesken** [comment]
Willl be fixed by an SDK update
