### ISSUE TITLE
Downloadable font: Bad sTypoLineGap

### ISSUE THREAD

**Issue by ale5000-git** [inpsyde/backwpup#63]
Here what Firefox say:
`downloadable font: OS/2: Bad sTypoLineGap, setting it to 0: -64 (font-family: "backwpup" style:normal weight:normal stretch:normal src index:1) source: /wp-content/plugins/backwpup/assets/fonts/backwpup.ttf`

**Comment by widoz** [comment]
Hi @ale5000-git may you try again with the latest 3.6.7?

**Comment by ale5000-git** [comment]
It should be fine now, thanks.
