### ISSUE TITLE
Temporary split files are filling the uploads folder and the server HDD

### ISSUE THREAD

**Issue by rene-hermenau** [inpsyde/backwpup#66]
In Backwpup 4.3.5 backup files are generated in the uploads folder which are not cleaned up. Last night this crashed my one of my sites because the HDD was full because of those files.

The backup file limit is 1 but there are multiple of these files.  

![backwpup](https://user-images.githubusercontent.com/878194/39229975-1eb5d30c-4865-11e8-8d3b-98a4de601f9e.png)

File permission of the folder is 755

**Comment by widoz** [comment]
Hi @rene-hermenau may you check with the latest 3.6.7 version? I think you meant 3.4.5 right?

**Comment by rene-hermenau** [comment]
Yes, that's what I meant. I did not experience that issue again so I close it for now.
