### ISSUE TITLE
Failed opening required autoload_real.php

### ISSUE THREAD

**Issue by jbarbede** [inpsyde/backwpup#68]
The latest version, 3.5.0 broke one of the websites I'm maintaining.

I am not sure what's happening but the log file shows that error:

`[16-May-2018 22:23:55 UTC] PHP Fatal error:  require_once(): Failed opening required '/home/[user]/public_html/wp-content/plugins/backwpup/vendor/composer/autoload_real.php' (include_path='.:/opt/alt/php71/usr/share/pear') in /home/[user]/public_html/wp-content/plugins/backwpup/vendor/autoload.php on line 5`

**Comment by widoz** [comment]
Hi @jbarbede please try with the latest version also, since this is a source repo, if you cloned the repo you have to run `composer install`, otherwise you can use the package attached to the release https://github.com/inpsyde/backwpup/releases/download/3.6.7/backwpup.zip

**Comment by Abdul-fatai** [comment]
To solve it just go to the root of your project and run on the command line:
`composer install`
