### ISSUE TITLE
Backup before automatically update

### ISSUE THREAD

**Issue by bueltge** [inpsyde/backwpup#7]
Backup automatisch erstellen, bevor das WP Autoupdate, seit 3.7 im Core, los läuft, um so den letzten Stand im Backup zu haben.

``` php
add_filter( 'schedule_event', 'my_backup_scheduler', 10, 1 );
function my_backup_scheduler( $event ) {
    // 'wp_maybe_auto_update' is the cron hook for the auto update process
    if ( 'wp_maybe_auto_update' !== $event['hook'] )
        return;

    wp_schedule_single_event( $event['timestamp'] - 5 * MINUTE_IN_SECONDS, 'my_backup' );
}


add_action( 'my_backup', 'my_backup' );
function my_backup() {
    // BackWPup Workflow
}
```

**Comment by janmyszkier** [comment]
Personally I think this is not needed feature. 
- backups should be made as often as possible (daily or more often) and no "hook" will save you. Especially the site could break before both core update, theme update or plugin update.
- nothing should be tested on production, so if you're not sure your site breaks, and you worry about it, use DEV server.

**Comment by bueltge** [comment]
Old, not in focus and not relevant for the timeline.
