### ISSUE TITLE
PHP Parse Error in 3.5 Broke Site

### ISSUE THREAD

**Issue by jmihalik** [inpsyde/backwpup#70]
Updated to 3.5 and it broke my site. All pages returned 500 errors, including admin pages, until I disabled the plugin from the console. Log shows the following:

PHP message: PHP Parse error:  syntax error, unexpected '[', expecting ')' in /var/www/website/wp-content/plugins/backwpup/vendor/guzzlehttp/promises/src/functions.php on line 45" while reading response header from upstream

I'm running PHP 5.3.10.

**Comment by widoz** [comment]
Hi @jmihalik could you please try with the latest 3.6.7 version? We have removed `guzzlehttp` and using `guzzle/guzzle` because of php compatibilities.

**Comment by jmihalik** [comment]
This was nearly a year ago. I'm no longer on that version of PHP. 🤷🏻‍♀️ The newest version of the plugin seems fine on my newer PHP.
