### ISSUE TITLE
Backup to azure not working, when TLS/HTTPS is forced in the backend

### ISSUE THREAD

**Issue by a3rosol** [inpsyde/backwpup#76]
Hi!
As the title says, the backup to azure blob doesn't work (error 400) when the azure account has only allowed https connections. It appears, backwpup tries to connect via http

**Comment by masterminduday** [comment]
I too am facing the same issue. My Azure storage is only HTTPS and unable to upload backup. I also get 400 error code.

**Comment by jartes** [comment]
I'm interested too about this issue. I'm having the same problem uploading backups to MS Azure. Thanks for solving it @markheydon :)

**Comment by VaclavElias** [comment]
Thank you @markheydon. This worked for me. I had to update my plugin manually. Hope it will be merged soon?

**Comment by jartes** [comment]
Submitted a new PR (#87) adding an option to choose between http and https :)
