### ISSUE TITLE
Add DigitalOcean Spaces to S3 destination

### ISSUE THREAD

**Issue by paullryan** [inpsyde/backwpup#79]
DigitalOcean now has an object storage mechanism using the S3 style api and would make a great addition to the S3 destination.

See https://www.digitalocean.com/docs/spaces/  

URLS are https://<your-space-name>.<region>.digitaloceanspaces.com (regions with spaces support are sfo2, nyc3, ams3, sgp1)

**Comment by noplanman** [comment]
@paullryan Take a look at my latest PR #82 :wink:

**Comment by paullryan** [comment]
@noplanman looks good to me, will close when that is merged.

**Comment by danielhuesken** [comment]
We will add it
