### ISSUE TITLE
Allow fully custom S3 settings

### ISSUE THREAD

**Issue by noplanman** [inpsyde/backwpup#81]
As the online storage world is growing, there are more and more S3 compatible services out there, so being able to set totally custom S3 URL and region would open up the possibilities to make use of them.
Having a limited drop-down list of available options doesn't allow for all these other services.

Or at least add WP filters to allow easy extension of the possible options :+1: 

Related: #57, #79

**Comment by widoz** [comment]
Hi @noplanman this refers to #82 right?

**Comment by danielhuesken** [comment]
Will be done in a similar way. Hofully in the next release it is there.
